import { ProductType } from "../types/types";

export const products: ProductType[] = [
  {
    id: "101",
    productName: "Apple MacBook Pro 16″",
    price: 2499.99,
    rating: 5,
    ratingCount: 1325,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Laptops",
    piece: 12,
    availableColor: ["#5c5c5c", "#c0c0c0"],
  },
  {
    id: "102",
    productName: "Samsung Galaxy S23 Ultra",
    price: 1199.99,
    rating: 4.5,
    ratingCount: 2140,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Smartphones",
    piece: 30,
    availableColor: ["#000000", "#2e8b57", "#e6e6fa", "#f5f5dc"],
  },
  {
    id: "103",
    productName: "Sony WH-1000XM5 Headphones",
    price: 379.99,
    rating: 4.8,
    ratingCount: 845,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Audio",
    piece: 18,
    availableColor: ["#000000", "#c0c0c0"],
  },
  {
    id: "104",
    productName: "GoPro HERO11 Black",
    price: 399.99,
    rating: 4.7,
    ratingCount: 523,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Cameras",
    piece: 9,
    availableColor: ["#000000"],
  },
  {
    id: "105",
    productName: "Kindle Paperwhite 11th Gen",
    price: 139.99,
    rating: 4.6,
    ratingCount: 920,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Tablets",
    piece: 25,
    availableColor: ["#000000"],
  },
  {
    id: "106",
    productName: "Fitbit Versa 4",
    price: 199.95,
    rating: 4.3,
    ratingCount: 670,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Wearables",
    piece: 40,
    availableColor: ["#4b4b4b", "#ffc0cb", "#0000ff"],
  },
  {
    id: "107",
    productName: "DJI Mini 4 Pro Drone",
    price: 799.0,
    rating: 4.9,
    ratingCount: 307,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Drones",
    piece: 5,
    availableColor: ["#808080"],
  },
  {
    id: "108",
    productName: "Anker PowerCore 20000mAh",
    price: 49.99,
    rating: 4.4,
    ratingCount: 1241,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Accessories",
    piece: 100,
    availableColor: ["#000000", "#ffffff"],
  },
  {
    id: "109",
    productName: "Logitech MX Master 3S Mouse",
    price: 99.99,
    rating: 4.8,
    ratingCount: 1830,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Accessories",
    piece: 65,
    availableColor: ["#000000", "#808080"],
  },
  {
    id: "110",
    productName: "Apple iPad Pro 12.9″",
    price: 1099.99,
    rating: 4.9,
    ratingCount: 2150,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Tablets",
    piece: 15,
    availableColor: ["#ffffff", "#c0c0c0"],
  },
  {
    id: "111",
    productName: "Sony PlayStation 5",
    price: 499.99,
    rating: 4.9,
    ratingCount: 5000,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Gaming",
    piece: 8,
    availableColor: ["#ffffff"],
  },
  {
    id: "112",
    productName: "Xbox Series X",
    price: 499.0,
    rating: 4.7,
    ratingCount: 4200,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Gaming",
    piece: 10,
    availableColor: ["#000000"],
  },
  {
    id: "113",
    productName: "Apple Watch Series 9",
    price: 399.0,
    rating: 4.6,
    ratingCount: 1600,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Wearables",
    piece: 35,
    availableColor: ["#000000", "#ff0000", "#00ff00"],
  },
  {
    id: "114",
    productName: "Bose QuietComfort Earbuds II",
    price: 279.0,
    rating: 4.5,
    ratingCount: 740,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Audio",
    piece: 22,
    availableColor: ["#000000", "#ffffff"],
  },
  {
    id: "115",
    productName: "Canon EOS R7 Camera",
    price: 1499.0,
    rating: 4.8,
    ratingCount: 420,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Cameras",
    piece: 6,
    availableColor: ["#000000"],
  },
  {
    id: "116",
    productName: "Apple AirPods Pro (2nd Gen)",
    price: 249.0,
    rating: 4.7,
    ratingCount: 3100,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Audio",
    piece: 50,
    availableColor: ["#ffffff"],
  },
  {
    id: "117",
    productName: "Samsung Galaxy Tab S9 Ultra",
    price: 1399.0,
    rating: 4.6,
    ratingCount: 1200,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Tablets",
    piece: 14,
    availableColor: ["#000000", "#808080"],
  },
  {
    id: "118",
    productName: "Nikon Z6 II Mirrorless Camera",
    price: 1999.0,
    rating: 4.7,
    ratingCount: 390,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Cameras",
    piece: 7,
    availableColor: ["#000000", "#c0c0c0"],
  },
  {
    id: "119",
    productName: "Razer Blade 15 Gaming Laptop",
    price: 2399.0,
    rating: 4.8,
    ratingCount: 860,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Laptops",
    piece: 11,
    availableColor: ["#000000"],
  },
  {
    id: "120",
    productName: "Apple iPhone 15 Pro Max",
    price: 1299.0,
    rating: 4.9,
    ratingCount: 2750,
    image:
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-wallpaper-screen_11102020_big.jpg.large.jpg",
    category: "Smartphones",
    piece: 20,
    availableColor: ["#000000", "#c0c0c0", "#b87333"],
  },
];
