import { MemberType } from "../types/types";

export const teamMember: MemberType[] = [
  {
    first_name: "Jason",
    last_name: "Price",
    email: "janick_parisian@yahoo.com",
    position: "Admin",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/admin.svg",
  },
  {
    first_name: "Jukkoe",
    last_name: "Sisao",
    email: "sibyl_kozey@gmail.com",
    position: "CEO",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/seo.svg",
  },
  {
    first_name: "Harriet",
    last_name: "King",
    email: "nadia_block@hotmail.com",
    position: "CTO",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/cto.svg",
  },
  {
    first_name: "Lenora",
    last_name: "Benson",
    email: "feil.wallace@kunde.us",
    position: "Lead",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/lead.svg",
  },
  {
    first_name: "Olivia",
    last_name: "Reese",
    email: "kemmer.hattie@cremin.us",
    position: "Strategist",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/strategist.svg",
  },
  {
    first_name: "Bertha",
    last_name: "Valdez",
    email: "loraine.koelpin@tromp.io",
    position: "CEO",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/ceo.svg",
  },
  {
    first_name: "Lily",
    last_name: "French",
    email: "lucienne.herman@hotmail.com",
    position: "Strategist",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/strategist2.svg",
  },
  {
    first_name: "Howard",
    last_name: "Adkins",
    email: "wiegand.leonor@herman.us",
    position: "CEO",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/seo2.svg",
  },
  {
    first_name: "Lenora",
    last_name: "Benson",
    email: "feil.wallace@kunde.us",
    position: "Lead",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/lead.svg",
  },
  {
    first_name: "George",
    last_name: "Bryant",
    email: "delmer.kling@gmail.com",
    position: "Social Media",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/social_media.svg",
  },
  {
    first_name: "Patrick",
    last_name: "Padilla",
    email: "delmer.kling@gmail.com",
    position: "Social Media",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/social_media1.svg",
  },
  {
    first_name: "Earl",
    last_name: "Bowman",
    email: "waino_altenwerth@nicolette.tv",
    position: "Digital Marketer",
    phone_number: "+1 234 567 890",
    gender: "Male",
    image: "/digital_marketer.svg",
  },
];
